intf_libs = # Interface dependencies
impl_libs = libuuid%lib{uuid} # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

# Public headers.
#
pub = [dir_path] ../../../include/libcppdotnet/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

./: lib{cppdotnet}

#./: {Numerics/} {Collections/} {Text/} {IO/}

lib{cppdotnet}: mxx{**} cxx{**} $impl_libs $intf_libs

# Private headers and sources as well as dependencies.
#
#./: lib{cppdotnet}: libul{cppdotnet}: {hxx ixx txx mxx}{** -**.test...} $impl_libs $intf_libs

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

{bmia obja}{*}: cxx.poptions += -DLIBCPPDOTNET_STATIC_BUILD
{bmis objs}{*}: cxx.poptions += -DLIBCPPDOTNET_SHARED_BUILD

import libs += libuuid.a

# Export options.
#
lib{cppdotnet}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs = $intf_libs
}

liba{cppdotnet}: cxx.export.poptions += -DLIBCPPDOTNET_STATIC
libs{cppdotnet}: cxx.export.poptions += -DLIBCPPDOTNET_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{cppdotnet}: bin.lib.version = "-$version.project_id"
else
  lib{cppdotnet}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false

mxx{*}:
{
  install         = include/libcppdotnet/
  install.subdirs = true
}
