import lib = libcppdotnet%lib{cppdotnet}

./: exe{TestException}: cxx{TestException} $lib
./: exe{TestDelegates}: cxx{TestDelegates} $lib
./: exe{TestTimeSpan}: cxx{TestTimeSpan} mxx{Utility} $lib
./: exe{TestTimeOnly}: cxx{TestTimeOnly} mxx{Utility} $lib
./: exe{TestDateOnly}: cxx{TestDateOnly} mxx{Utility} $lib
./: exe{TestDateTime}: cxx{TestDateTime} mxx{Utility} $lib
./: exe{TestDateTimeOffset}: cxx{TestDateTimeOffset} mxx{Utility} $lib
./: exe{TestValueTuple}: cxx{TestValueTuple} $lib
./: exe{TestEnum}: cxx{TestEnum} $lib
./: exe{TestBitConverter}: cxx{TestBitConverter} $lib
./: exe{TestConvert}: cxx{TestConvert} $lib
./: exe{TestSpan}: cxx{TestSpan} $lib
./: exe{TestReadOnlySpan}: cxx{TestReadOnlySpan} $lib
./: exe{TestVersion}: cxx{TestVersion} $lib
./: exe{TestNullable}: cxx{TestNullable} $lib
#./: exe{TestGuid}: cxx{TestGuid} $lib
