pub_hdrs = {hxx ixx txx}{** -version} hxx{version}

./: $pub_hdrs

hxx{version}: in{version} $src_root/manifest

# Install into the libcppdotnet/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libcppdotnet/
  install.subdirs = true
}
